# authorizer-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: vault-credentials
  namespace: authorizer
type: Opaque
data:
  # These are base64 encoded values
  VAULT_TOKEN: bXlyb290  # "myroot" in base64
  VAULT_DEV_ROOT_TOKEN_ID: bXlyb290  # "myroot" in base64