# authorizer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashvault-deployment
  namespace: authorizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashvault
  template:
    metadata:
      labels:
        app: hashvault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:latest  # Using the latest HashiCorp Vault image
        ports:
        - containerPort: 8200
          name: vault-port
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          valueFrom:
            secretKeyRef:
              name: vault-credentials
              key: VAULT_DEV_ROOT_TOKEN_ID
        - name: VAULT_DEV_LISTEN_ADDRESS
          value: "0.0.0.0:8200"
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
        volumeMounts:
        - name: hashvault-storage
          mountPath: /vault/data
        readinessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
      volumes:
      - name: hashvault-storage
        persistentVolumeClaim:
          claimName: hashvault-pvc