# hashvault-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hashvault-pvc
  namespace: authorizer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi