apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: messaging
  labels:
    app: kafka-ui
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30006
  selector:
    app: kafka-ui
