apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: messaging
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30005
  selector:
    app: kafka
