apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kafka-autoscaler
  namespace: messaging
  labels:
    app: kafka
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
