# combined-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: database
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXNwYXNzd29yZA==  # postgrespassword
  POSTGRES_USER: cG9zdGdyZXN1c2Vy  # postgresuser
  POSTGRES_DB: cG9zdGdyZXNkYg==  # postgresdb
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
  namespace: database
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29t  # admin@admin.com
  PGADMIN_DEFAULT_PASSWORD: cGdhZG1pbnBhc3N3b3Jk  # pgadminpassword