apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: authorizer
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: keycloak
