apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  namespace: authorizer
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:latest
        command: ["/opt/keycloak/bin/kc.sh"]
        args: ["start"]  # Use 'start' instead of 'start-dev' for production
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: keycloak-admin-creds
              key: KEYCLOAK_ADMIN
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-admin-creds
              key: KEYCLOAK_ADMIN_PASSWORD
        # Add these required environment variables
        - name: KC_PROXY
          value: "edge"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        volumeMounts:
        - name: keycloak-storage
          mountPath: /opt/keycloak/data
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 700m
            memory: 1Gi
      volumes:
      - name: keycloak-storage
        persistentVolumeClaim:
          claimName: keycloak-pvc
