apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Only one node can access it at a time
  resources:
    requests:
      storage: 2Gi  # Request 2 GiB of storage