apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: messaging
spec:
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
    nodePort: 30007  
    name: amqp
  - protocol: TCP
    port: 15672
    targetPort: 15672
    nodePort: 30008  
    name: http
  type: NodePort