apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: database
  labels:
    type: local-mac
    app: mysql-pv
spec:
  storageClassName: local-mac
  capacity:
    storage: 10Gi  # Must match your PVC request
  accessModes:
    - ReadWriteOnce  # Must match your PVC accessModes
  persistentVolumeReclaimPolicy: Retain # Or Delete, if you prefer to delete storage on volume release
  hostPath:
    path: /Users/siddharthlucky/Docker-Kube-StorageDrive/mysql-storage  # <-------- Change This!