apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: database
  labels:
    app: mysql
spec:
  storageClassName: local-mac
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
